"""Add priority scoring

Revision ID: 48eeec0587e6
Revises: 8566915ac37b
Create Date: 2026-03-02 21:40:46.068073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48eeec0587e6'
down_revision: Union[str, Sequence[str], None] = '8566915ac37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('priority_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'priority_level')
    op.drop_column('complaints', 'priority_score')
    # ### end Alembic commands ###
