"""Update building model

Revision ID: 4efd0e0c0f09
Revises: e3023aad6b59
Create Date: 2026-03-02 21:28:06.801516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efd0e0c0f09'
down_revision: Union[str, Sequence[str], None] = 'e3023aad6b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('floor_count', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('buildings', 'room_number')
    op.drop_column('buildings', 'floor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('buildings', sa.Column('room_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('buildings', 'created_at')
    op.drop_column('buildings', 'floor_count')
    # ### end Alembic commands ###
