"""Add staff assignment to complaints

Revision ID: 8566915ac37b
Revises: 4efd0e0c0f09
Create Date: 2026-03-02 21:35:52.338144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8566915ac37b'
down_revision: Union[str, Sequence[str], None] = '4efd0e0c0f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'assigned_to')
    # ### end Alembic commands ###
