"""Update complaint structure

Revision ID: e3023aad6b59
Revises: c435b89365dc
Create Date: 2026-02-28 12:09:56.630444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3023aad6b59'
down_revision: Union[str, Sequence[str], None] = 'c435b89365dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               type_=sa.String(),
               nullable=False)
    op.drop_column('complaints', 'priority')
    op.drop_column('complaints', 'image_url')
    op.add_column('ticket_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('ticket_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ticket_logs', 'old_status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ticket_logs', 'new_status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('ticket_logs_changed_by_fkey'), 'ticket_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_logs', 'users', ['updated_by'], ['id'])
    op.drop_column('ticket_logs', 'changed_by')
    op.drop_column('ticket_logs', 'timestamp')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'ADMIN', 'STAFF', name='userrole'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('STUDENT', 'ADMIN', 'STAFF', name='userrole'),
               nullable=True)
    op.add_column('ticket_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('ticket_logs', sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_logs_changed_by_fkey'), 'ticket_logs', 'users', ['changed_by'], ['id'])
    op.alter_column('ticket_logs', 'new_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               existing_nullable=True)
    op.alter_column('ticket_logs', 'old_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               existing_nullable=True)
    op.drop_column('ticket_logs', 'updated_at')
    op.drop_column('ticket_logs', 'updated_by')
    op.add_column('complaints', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'), autoincrement=False, nullable=True))
    op.alter_column('complaints', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'),
               nullable=True)
    # ### end Alembic commands ###
